on:
  push:
      branches:
          - main
      tags:
          - "v*"
  pull_request:
      branches:
          - "*"

jobs:
  main:
    name: MealPlanner CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: yarn install
      run: yarn install

    - name: TypeScript
      run: yarn tsc

    - name: ESLint
      run: yarn lint
